before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/steamquery/steamquery.go

    flags:
      - -trimpath

    env:
      - CGO_ENABLED=0

    ldflags:
      - -s -w -X main.buildVersion={{.Version}} -X main.buildDate={{.Date}} -X main.buildGitCommit={{.Commit}}

    goos:
      - darwin
      - linux
      - windows

    goarch:
      - amd64
      - arm64

    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
