name: golangci-build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  build:
    name: build
    if: ${{ github.ref == 'refs/heads/main' }}
    strategy:
      matrix:
        go: [1.20.4, 1.20.3]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - run: go clean -modcache -cache -i
      - run: go mod tidy
      - run: go get -v ./...
      - run: go build -v -o steamquery_test_build ./...